language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run production 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: main